/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package model;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CardSuite extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4158790927888680758L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CardSuite\",\"namespace\":\"model\",\"fields\":[{\"name\":\"suit\",\"type\":\"string\",\"doc\":\"The suit of the card\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The suit of the card */
  @Deprecated public java.lang.CharSequence suit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CardSuite() {}

  /**
   * All-args constructor.
   * @param suit The suit of the card
   */
  public CardSuite(java.lang.CharSequence suit) {
    this.suit = suit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return suit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: suit = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'suit' field.
   * @return The suit of the card
   */
  public java.lang.CharSequence getSuit() {
    return suit;
  }

  /**
   * Sets the value of the 'suit' field.
   * The suit of the card
   * @param value the value to set.
   */
  public void setSuit(java.lang.CharSequence value) {
    this.suit = value;
  }

  /**
   * Creates a new CardSuite RecordBuilder.
   * @return A new CardSuite RecordBuilder
   */
  public static model.CardSuite.Builder newBuilder() {
    return new model.CardSuite.Builder();
  }

  /**
   * Creates a new CardSuite RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CardSuite RecordBuilder
   */
  public static model.CardSuite.Builder newBuilder(model.CardSuite.Builder other) {
    return new model.CardSuite.Builder(other);
  }

  /**
   * Creates a new CardSuite RecordBuilder by copying an existing CardSuite instance.
   * @param other The existing instance to copy.
   * @return A new CardSuite RecordBuilder
   */
  public static model.CardSuite.Builder newBuilder(model.CardSuite other) {
    return new model.CardSuite.Builder(other);
  }

  /**
   * RecordBuilder for CardSuite instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CardSuite>
    implements org.apache.avro.data.RecordBuilder<CardSuite> {

    /** The suit of the card */
    private java.lang.CharSequence suit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(model.CardSuite.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.suit)) {
        this.suit = data().deepCopy(fields()[0].schema(), other.suit);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CardSuite instance
     * @param other The existing instance to copy.
     */
    private Builder(model.CardSuite other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.suit)) {
        this.suit = data().deepCopy(fields()[0].schema(), other.suit);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'suit' field.
      * The suit of the card
      * @return The value.
      */
    public java.lang.CharSequence getSuit() {
      return suit;
    }

    /**
      * Sets the value of the 'suit' field.
      * The suit of the card
      * @param value The value of 'suit'.
      * @return This builder.
      */
    public model.CardSuite.Builder setSuit(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.suit = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'suit' field has been set.
      * The suit of the card
      * @return True if the 'suit' field has been set, false otherwise.
      */
    public boolean hasSuit() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'suit' field.
      * The suit of the card
      * @return This builder.
      */
    public model.CardSuite.Builder clearSuit() {
      suit = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public CardSuite build() {
      try {
        CardSuite record = new CardSuite();
        record.suit = fieldSetFlags()[0] ? this.suit : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
